public class Courses {

    public static final String[] COURSES =

            {
                    "Anthropology",
                    "Archaeology",
                    "Architecture",
                    "Art-Design",
                    "Biochemistry",
                    "Biology",
                    "Biomedical Sciences",
                    "Business Studies",
                    "Chemistry",
                    "Chinese",
                    "Classics",
                    "Computer Science",
                    "Dentistry",
                    "Design",
                    "Drama",
                    "Economics",
                    "Education",
                    "Electronics",
                    "Engineering",
                    "English",
                    "Environmental Science",
                    "Fine Art",
                    "French",
                    "Geography",
                    "Geology",
                    "Geophysics",
                    "German",
                    "Health Science",
                    "History",
                    "History of Art",
                    "Human Sciences",
                    "ICT",
                    "Law",
                    "Linguistics",
                    "Mathematics",
                    "Media Studies",
                    "Medicine",
                    "Music",
                    "Music Technology",
                    "Natural Sciences",
                    "Nursing",
                    "Occupational Therapy",
                    "Oceanography",
                    "Pharmacy",
                    "Photography",
                    "Philosophy",
                    "Physiotherapy",
                    "Physical Education",
                    "Physics",
                    "Politics",
                    "Psychology",
                    "Radiography and Radiotherapy",
                    "Religious Studies",
                    "Sociology",
                    "Spanish",
                    "Speech and Language Therapy",
                    "Tourism",
                    "Veterinary Medicine"
            };

}
